# Generated by Django 5.0.9 on 2026-02-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit_score',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fraud_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_fraud',
            field=models.BooleanField(default=False),
        ),
    ]
