# Generated by Django 5.0.9 on 2026-03-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Credit'), ('OUT', 'Debit')], default='IN', max_length=3),
        ),
    ]
