# Generated by Django 5.0.9 on 2025-12-03 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.customer'),
        ),
    ]
