# Generated by Django 5.0.9 on 2025-12-03 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_account_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
