# Generated by Django 5.0.9 on 2025-12-03 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_rename_customer_account_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='created_at',
        ),
    ]
