# Generated by Django 5.0.9 on 2025-12-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_customers', models.IntegerField(default=0)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistique du Dashboard',
                'verbose_name_plural': 'Statistiques du Dashboard',
                'ordering': ['-updated_at'],
            },
        ),
    ]
