# Generated by Django 5.0.9 on 2025-12-10 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_payment_date_alter_payment_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
