# Generated by Django 5.0.9 on 2026-02-11 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=150)),
                ('device', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('risk_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('suspect', 'Suspect'), ('fraud', 'Frauduleux')], default='normal', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
